const express = require('express')
const router = express.Router()
const tier_controler = require('../controllers/tier')
router.post('/AaddTier2',tier_controler.AaddTier2)
router.post('/MaddTier2',tier_controler.MaddTier2)
router.post('/DaddTier2',tier_controler.DaddTier2)
router.post('/getTier1',tier_controler.getTier1)
router.post('/getTier2',tier_controler.getTier2)
router.post('/AaddTier1',tier_controler.AaddTier1)
router.post('/MaddTier1',tier_controler.MaddTier1)
router.post('/DaddTier1',tier_controler.DaddTier1)
module.exports = router